version: '3'
services:
    jenkins:
        build: ./jenkins
        container_name: jenkins
        ports:
            - '8080:8080'
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
    server:
        build: ./server
        volumes: 
            - .:/usr/src/app/
            - /usr/src/app/node_modules
        ports:
            - '3000:3000'
        depends_on:
            - database
        environment:
            DATABASE_URL: jdbc:mysql://localhost:3306/user
    database:
        build: ./database
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql
volumes:
    jenkins-docker-certs:
    jenkins-data:
    my-db: