version: '3'
services:
    jenkins:
        build: ./jenkins
        container_name: jenkins
        ports:
            - '8080:8080'
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
    server:
        build: ./server
        container_name: server
        working_dir: /usr/src/app
        volumes: 
            - ./server/budgetish_react:/usr/src/app/
        ports:
            - '3000:3000'
            - '8081:8081'
        environment:
            DATABASE_URL: jdbc:mysql://localhost:3306/user
        stdin_open: true
        tty: true
    database:
        build: ./database
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'budgetish'
            MYSQL_PASSWORD: '5tgbnhy6%TGBNHY^'
            MYSQL_ROOT_PASSWORD: '5tgbnhy6%TGBNHY^'
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql
volumes:
    jenkins-docker-certs:
    jenkins-data:
    my-db: